Repository artsy/energy, pull requests merged in 2022-09, with the labels that each got.

#172 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#154 feat(MOPLAT-394): Share sheet for artwork screen
  docs/troubleshooting.md
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/screens/Artwork/AddArtworkToAlbum.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/sharedUI/screens/Artwork/EditArtworkInCms.tsx
  src/palette/svgs/ArtworkIcon.tsx
  src/palette/svgs/CloseIcon.tsx
Labels: Jira Synced

#168 fix: Hide price fix
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Squash On Green

#174 chore: remove dark mode tester
  src/app/AppProviders.tsx
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/store/Models/DevicePrefsModel.ts
Labels: Jira Synced

#179 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#180 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#166 refactor: Eslint fixes
  .eslintrc.js
  patches/@react-native-seoul+masonry-list+1.3.0.patch
  src/app/AppProviders.tsx
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/Auth/Login.tsx
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/Dev/InsteadOfStorybook.tsx
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tests.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tests.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/Artists/Artists.tests.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Settings/DarkModeSettings.tsx
  src/app/screens/HomeTabs/Settings/EditPresentationMode.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tests.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/HomeTabs/Shows/Shows.tests.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/items/AlbumListImage.tsx
  src/app/sharedUI/items/AlbumListItem.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ArtworkImageGridItem.tsx
  src/app/sharedUI/items/ArtworkItem.tests.tsx
  src/app/sharedUI/items/ArtworkItem.tsx
  src/app/sharedUI/items/DocumentGridItem.tests.tsx
  src/app/sharedUI/items/DocumentGridItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/app/sharedUI/molecules/ScrollableScreensView/Context.ts
  src/app/sharedUI/molecules/SettingsItem.tsx
  src/app/sharedUI/molecules/SwitchContainer.tsx
  src/app/sharedUI/screens/Artwork/AddArtworkToAlbum.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/sharedUI/screens/Artwork/ArtworkWebView.tsx
  src/app/sharedUI/screens/Artwork/EditArtworkInCms.tsx
  src/app/sharedUI/screens/InstallImage/InstallImage.tsx
  src/app/store/Models/AuthModel.ts
  src/app/store/Models/ConfigModel.ts
  src/app/store/Models/GlobalStoreModel.ts
  src/app/wrappers/SuspenseWrapper.tsx
  src/app/wrappers/TabsContainer.tsx
Labels: Squash On Green

#176 feat(moplat-394): margin, borderRadius
  src/app/sharedUI/screens/Artwork/Artwork.tsx
Labels: Jira Synced

#181 fix(palette): touchable color fix
  src/app/screens/Dev/FolioDesignLanguage.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced

#175 feat(moplat-379): dev menu
  ios/Podfile.lock
  package.json
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/store/Models/ConfigModel.ts
  src/app/store/Models/EnvironmentModel.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#189 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#191 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#192 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#165 feat(MOPLAT-352): Util function to retrieve the right size for artworks
  package.json
  src/app/relay/environment/createEnvironment.ts
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/items/AlbumListImage.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ArtworkItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/utils/imageSize.ts
  src/app/utils/loggers.ts
  src/palette/elements/Text/Text.tsx
Labels: Jira Synced

#183 fix: Album list image crop fix
  src/app/sharedUI/items/AlbumListItem.tsx
Labels: Jira Synced

#194 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#187 feat(MOPLAT-398): pass cookies in webview
  ios/Podfile.lock
  package.json
  src/app/navigation/MainNavigationStack.tsx
  src/app/sharedUI/screens/Artwork/ArtworkWebView.tsx
  src/app/store/Models/AuthModel.ts
  src/app/store/Models/EnvironmentModel.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#184 feat(MOPLAT-404): Markdown
  package.json
  src/app/sharedUI/molecules/Markdown.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/shared/utils/renderMarkdown.tsx
  yarn.lock
Labels: Jira Synced

#196 feat: moplat255: dev env
  src/app/store/Models/EnvironmentModel.ts
Labels: Jira Synced

#200 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#186 feat(MOPLAT-406): Shallow zoom for artworks and install shots - ReactNativeZoomableView
  package.json
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/sharedUI/items/ArtworkImageGridItem.tsx
  src/app/sharedUI/molecules/ImageModal.tsx
  src/app/sharedUI/molecules/ScrollableScreensView/LazyScreen.tsx
  src/app/sharedUI/molecules/index.ts
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/sharedUI/screens/InstallImage/InstallImage.tsx
  src/palette/Theme.tsx
  yarn.lock
Labels: Jira Synced

#202 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#203 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#204 moplat-412-select-mode-pt-1
  .eslintrc.js
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
  src/app/store/Models/GlobalStoreModel.ts
  src/app/store/Models/SelectModeModel.ts
Labels: Jira Synced

#210 feat(MOPLAT-412) button updates
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced

#212 fix: pass name down instead of querying, fix crash for hidden artists
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
Labels: Jira Synced, folio-bug-bash-1

#214 fix: bigger tap area on the more icon
  src/app/sharedUI/screens/Artwork/Artwork.tsx
Labels: folio-bug-bash-1

#211 feat: short splashscreen on dev
  ios/Energy/AppDelegate.m
Labels: folio-bug-bash-1

#213 fix: add missing count and crash on new album
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
Labels: Jira Synced, folio-bug-bash-1

#215 fix(MOPLAT-431): Opening a show with install shots goes straight to the install shot
  src/app/sharedUI/items/ArtworkImageGridItem.tsx
Labels: Jira Synced

#216 feat: add typecheck on prepush, and remove all types we had issues with for now
  .husky/pre-push
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/palette/Theme.tsx
  src/palette/elements/Checkbox/Checkbox.tsx
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  src/palette/elements/Radio/RadioButton.tsx
  src/palette/elements/Text/Typography-v1.tsx
  src/palette/icons.stories.tsx
  src/palette/organisms/screenStructure/Screen.stories.tsx
Labels: folio-bug-bash-1

#205 refactor(MOPLAT-423): get on models
  src/app/store/GlobalStore.tsx
  src/app/store/Models/AlbumsModel.ts
  src/app/store/Models/AuthModel.ts
  src/app/store/Models/ConfigModel.ts
  src/app/store/Models/GlobalStoreModel.ts
  src/app/store/Models/PresenationModeModel.tsx
Labels: Jira Synced

#219 WIP moplat-379-add-a-dev-menu-to-folio-1 devMode
  package.json
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/store/Models/ArtsyPrefsModel.ts
  src/app/store/Models/GlobalStoreModel.ts
  yarn.lock
Labels: Jira Synced

#223 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#225 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#222 feat(MOPLAT-421): Send Email pt 1: Customise email text
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/EmailScreen.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksAndArtists.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksBySameArtist.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/OneArtwork.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/store/Models/EmailModel.ts
  src/app/store/Models/GlobalStoreModel.ts
Labels: Jira Synced

#227 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#230 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#236 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#237 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#238 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#232 feat: MOPLAT-421 email part 1
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/EmailScreen.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksAndArtists.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksBySameArtist.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/OneArtwork.tsx
  src/app/store/Models/EmailModel.ts
Labels: Jira Synced
