Repository artsy/energy, pull requests merged in 2022-10, with the labels that each got.

#244 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#246 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#228 feat: qr code in presentation mode
  package.json
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  yarn.lock
Labels: Jira Synced

#239 feat: Select Mode Part 2
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/items/DocumentGridItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/app/sharedUI/molecules/BottomSheetModalView.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/store/Models/SelectModeModel.ts
Labels: Jira Synced

#248 fix: remove production check from dev menu
  src/app/screens/Dev/DevMenu.tsx
Labels: Squash On Green

#247 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#253 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#251 fix: Add to album flow
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/sharedUI/molecules/BottomSheetModalView.tsx
  src/app/sharedUI/screens/Artwork/AddArtworkToAlbum.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Jira Synced

#242 feat: MOPLAT-417 Send Email pt 2: Send Artwork(s) via email
  android/app/src/main/java/com/energy/MainActivity.java
  android/app/src/main/java/com/energy/MainApplication.java
  android/settings.gradle
  docs/troubleshooting.md
  ios/Energy.xcodeproj/project.pbxproj
  ios/Energy/AppDelegate.h
  ios/Energy/AppDelegate.m
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  package.json
  src/app/sharedUI/molecules/BottomSheetModalView.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  yarn.lock
Labels: Jira Synced

#256 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#255 feat: spacer from palette-mobile!
  jest.config.js
  package.json
  src/app/screens/Auth/Login.tsx
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/EmailScreen/EmailScreen.tsx
  src/app/screens/HomeTabs/Settings/DarkModeSettings.tsx
  src/app/screens/HomeTabs/Settings/EditPresentationMode.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/items/AlbumListItem.tsx
  src/app/sharedUI/items/ArtworkItem.tsx
  src/app/sharedUI/molecules/BottomSheetModalView.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/palette/atoms/Spacer/Spacer.tsx
  src/palette/atoms/Spacer/index.tsx
  src/palette/atoms/index.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/elements/EntityHeader/EntityHeader.tsx
  src/palette/elements/Header/ArtsyLogoHeader.tsx
  src/palette/elements/List/BulletedItem.tsx
  src/palette/organisms/screenStructure/Screen.tsx
  yarn.lock
Labels: Squash On Green

#261 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#262 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#258 feat(MOPLAT-415): Select mode part3
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/sharedUI/molecules/BottomSheetModalView.tsx
  src/app/sharedUI/screens/Artwork/AddArtworksToAlbum.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/index.ts
  src/app/store/Models/AlbumsModel.ts
Labels: Jira Synced, Squash On Green

#265 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#260 MOPLAT-417 one email subject
  src/app/sharedUI/screens/Artwork/Artwork.tsx
Labels: Jira Synced

#263 feat: old folio album migration
  .eslintrc.js
  .secrets.baseline
  ios/Energy.xcodeproj/project.pbxproj
  ios/NativeModules/ARTAlbumMigrationModule.h
  ios/NativeModules/ARTAlbumMigrationModule.m
  src/app/native_modules/ARTNativeModules.ts
  src/app/screens/Auth/Login.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/shared/utils/attemptAlbumMigration.ts
  src/shared/utils/renderMarkdown.tsx
Labels: Jira Synced

#267 fix: Spacing in Artwork content sheet
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Squash On Green

#269 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#271 fix: xcode build
  .gitignore
  HACKS.md
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/react-native+0.66.2.patch
  src/setupJest.ts
  yarn.lock
Labels: Squash On Green

#277 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#279 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#243 feat: tablet layout improvements
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/Albums.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/items/AlbumListItem.tsx
  src/app/sharedUI/items/ArtistListItem.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/setupJest.ts
Labels: Jira Synced

#280 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#281 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#278 fix: presentation mode toggles and tests cases
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tests.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/usePresentationFilteredArtworks.ts
  src/app/sharedUI/atoms/StatusDot.tsx
  src/app/sharedUI/items/ArtworkGridItem.tests.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ArtworkItem.tests.tsx
  src/app/sharedUI/items/ArtworkItem.tsx
  src/app/sharedUI/items/index.ts
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/Models/GlobalStoreModel.ts
  src/app/store/Models/PresentationModeModel.tsx
Labels: Jira Synced, Squash On Green

#284 fix: Album placeholder
  src/app/sharedUI/items/AlbumListItem.tsx
Labels: Jira Synced

#283 feat: Search part 1
  package.json
  src/app/navigation/Main.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Search/Search.tsx
  src/app/screens/HomeTabs/Search/SearchResult.tsx
  src/palette/elements/Pill/Pill.tests.tsx
  src/palette/elements/Pill/Pill.tsx
  src/palette/elements/Pill/index.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#288 chore: bump to xcode 14 on ci
  .circleci/config.yml
Labels: Squash On Green

#287 chore: update palette-mobile
  package.json
  yarn.lock
Labels: Squash On Green

#291 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#292 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
