Repository artsy/energy, pull requests merged in 2022-12, with the labels that each got.

#336 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#337 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#338 fix: remove unnecessary login check, add a reset button
  .secrets.baseline
  ios/NativeModules/ARTAlbumMigrationModule.m
  src/app/native_modules/ARTNativeModules.ts
  src/app/screens/Dev/DevMenu.tsx
  src/shared/utils/attemptAlbumMigration.ts
Labels: Jira Synced

#339 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#313 fix: select one pill at a time
  src/app/screens/HomeTabs/Search/Search.tsx
  src/app/screens/HomeTabs/Search/SearchPills.tsx
  src/app/screens/HomeTabs/Search/SearchResult.tsx
  src/app/screens/HomeTabs/Search/searchAtoms.ts
Labels: Jira Synced

#341 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#342 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#343 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#344 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#345 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#340 feat: API error screen
  src/app/navigation/Main.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/ErrorView.tsx
  src/app/wrappers/ErrorBoundayWrapper.tsx
Labels: Jira Synced

#347 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#346 feat: logout when token expires
  src/app/relay/environment/createEnvironment.ts
  src/app/relay/middlewares/checkAuthenticationMiddleware.ts
Labels: Jira Synced

#350 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#266 feat: moplat-417 Compose email with one artist and multiple artworks
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
Labels: Jira Synced

#351 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#353 fix: Album creation flow
  src/app/navigation/navAtoms.ts
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
Labels: Jira Synced, Squash On Green

#356 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#366 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#367 feat(flipper): Add flipper relay tools
  .vscode/settings.json
  package.json
  src/app/App.tsx
  src/app/system/flipper.ts
  yarn.lock
Labels: Squash On Green

#368 chore: update metaphysics graphql schema
  yarn.lock
Labels: Squash On Green

#349 fix: log out users that are not partners
  src/app/navigation/Main.tsx
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/wrappers/ErrorBoundary.tsx
Labels: Jira Synced

#372 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#371 chore(tooling): Enforce and support automatic absolute imports and ESlint cleanup
  .eslintrc.js
  .vscode/settings.json
  docs/pull_request_template.md
  package.json
  yarn.lock
Labels: Squash On Green

#360 fix: dots position alignment in artwork screen
  src/app/sharedUI/screens/Artwork/Artwork.tsx
Labels: Jira Synced

#354 fix: create button background color fix in dark mode
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
Labels: Jira Synced

#361 fix: disable screen landscape mode
  android/app/src/main/AndroidManifest.xml
  ios/Energy/Info.plist
Labels: Jira Synced

#375 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#376 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#378 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#369 feat(MOPLAT-535): Add offline sync support
  .circleci/config.yml
  .eslintrc.js
  dangerfile.ts
  ios/Podfile.lock
  package.json
  src/app/navigation/Main.tsx
  src/app/relay/RelayProvider.tsx
  src/app/relay/environment/createEnvironment.ts
  src/app/relay/useSystemQueryLoader.ts
  src/app/relay/useSystemRelayEnvironment.ts
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/Artists/Artists.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/GlobalStore.tsx
  src/app/store/Models/GlobalStoreModel.ts
  src/app/store/Models/NetworkStatusModel.ts
  src/app/system/sync/fileCache.ts
  src/app/system/sync/syncManager.ts
  src/app/system/sync/utils/fetchOrCatch.ts
  src/app/system/sync/utils/mapAsync.ts
  src/app/system/useNetworkStatusListener.ts
  yarn.lock
Labels: Jira Synced

#323 fix: dont let double titles or zero titles appear
  src/palette/organisms/Screen/hooks.ts
Labels: Jira Synced

#364 fix: artwork content screen big fixes
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Jira Synced

#362 feat: test case for authentication signout middleware
  package.json
  src/app/relay/middlewares/checkAuthenticationMiddleware.tests.tsx
  src/app/relay/middlewares/checkAuthenticationMiddleware.ts
  src/app/store/GlobalStore.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#381 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#383 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#384 fix: pass name to avoid MP error
  src/app/navigation/Main.tsx
  src/app/screens/Auth/Login.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/system/sync/syncManager.ts
  src/app/system/sync/utils/fetchOrCatch.ts
Labels: Squash On Green

#385 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#374 feat: offline images
  .circleci/config.yml
  dangerfile.ts
  index.js
  ios/Podfile.lock
  package.json
  src/app/App.tsx
  src/app/navigation/Main.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumInstalls.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Search/Search.tsx
  src/app/screens/HomeTabs/Search/SearchResult.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/sharedUI/items/AlbumListImage.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ArtworkImageGridItem.tsx
  src/app/sharedUI/items/DocumentGridItem.tests.tsx
  src/app/sharedUI/items/DocumentGridItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/app/sharedUI/molecules/ImageModal.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/selectModeAtoms.ts
  src/app/system/sync/fileCache.ts
  src/app/system/sync/syncManager.ts
  src/app/system/sync/utils/asyncIterators.ts
  src/app/system/sync/utils/fetchOrCatch.ts
  src/app/system/sync/utils/mapAsync.ts
  src/app/wrappers/CachedImage.tsx
  src/app/wrappers/ErrorBoundary.tsx
  src/setupJest.ts
  yarn.lock
Labels: Squash On Green

#387 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#388 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#390 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#392 fix: image size for more images
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/system/sync/syncManager.ts
Labels: Squash On Green

#393 fix(artwork): Move <Artwork /> to /Screens
  src/app/Navigation.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/screens/Artwork/ArtworkContent/__tests__/ArtworkContent.tests.tsx
  src/app/screens/Artwork/ArtworkWebView.tsx
  src/app/screens/Artwork/EditArtworkInCms.tsx
  src/app/system/sync/syncManager.ts
Labels: Squash On Green

#399 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#391 feat: add documents in the offline cache
  HACKS.md
  ios/Podfile.lock
  jest.config.js
  package.json
  patches/rn-fetch-blob+0.12.0.patch
  src/app/Providers.tsx
  src/app/components/AddItemsToAlbum.tsx
  src/app/components/Items/DocumentGridItem.tsx
  src/app/components/Items/__tests__/DocumentGridItem.tests.tsx
  src/app/screens/Dev/BrowseOfflineCache.tsx
  src/app/screens/Dev/StorybookNavigation.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/system/store/GlobalStore.tsx
  src/app/system/store/Models/AlbumsModel.ts
  src/app/system/store/Models/GlobalStoreModel.ts
  src/app/system/store/Models/SelectModeModel.ts
  src/app/system/sync/fileCache.ts
  src/app/system/sync/utils/tree.ts
  src/app/system/wrappers/CachedImage.tsx
  src/app/utils/assertNever.ts
  src/global.d.ts
  src/palette/organisms/Screen/exposed/Body.tsx
  src/setupJest.ts
  src/typings/assertNever.d.ts
  src/typings/deepPartial.d.ts
  src/typings/global.d.ts
  src/typings/vars.d.ts
  yarn.lock
Labels: Squash On Green

#401 refactor(nav): Introduce navigation composition
  src/app/Navigation.tsx
  src/app/screens/Albums/AddItemsToAlbum.tsx
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/Albums/AlbumTabs/AlbumInstalls.tsx
  src/app/screens/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/Albums/Albums.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/Albums/CreateOrEditAlbum/useArtworksByMode.ts
  src/app/screens/Albums/navigation.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tests.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/EmailScreen/EmailScreen.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksAndArtists.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/EmailScreen/MultipleArtworksBySameArtist.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/EmailScreen/OneArtwork.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/EmailScreen/navigation.tsx
  src/app/screens/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/Artists/ArtistTabs/ArtistShows/ArtistShows.tests.tsx
  src/app/screens/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artists/Artists.tests.tsx
  src/app/screens/Artists/Artists.tsx
  src/app/screens/Artists/navigation.tsx
  src/app/screens/Artwork/navigation.tsx
  src/app/screens/Auth/navigation.tsx
  src/app/screens/Dev/InsteadOfStorybook.tsx
  src/app/screens/Dev/navigation.tsx
  src/app/screens/HomeTabs.tsx
  src/app/screens/Search/Search.tsx
  src/app/screens/Search/SearchPills.tsx
  src/app/screens/Search/SearchResult.tsx
  src/app/screens/Search/navigation.tsx
  src/app/screens/Search/searchAtoms.ts
  src/app/screens/Settings/DarkModeSettings.tsx
  src/app/screens/Settings/EditPresentationMode.tsx
  src/app/screens/Settings/Settings.tsx
  src/app/screens/Settings/navigation.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tests.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/Shows/ShowTabs/ShowInstalls/ShowInstalls.tests.tsx
  src/app/screens/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/Shows/Shows.tests.tsx
  src/app/screens/Shows/Shows.tsx
  src/app/screens/Shows/navigation.tsx
  src/app/system/sync/syncManager.ts
  src/app/utils/hooks/usePresentationFilteredArtworks.ts
Labels: Squash On Green

#407 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#408 fix: dark mode ui tweaks
  package.json
  src/app/components/BottomSheetModalView.tsx
  src/app/components/Items/AlbumListItem.tsx
  yarn.lock
Labels: Jira Synced

#406 fix: floating back button with bg color
  src/app/screens/Artwork/Artwork.tsx
Labels: Jira Synced, Squash On Green

#405 fix: docs now work
  ios/Podfile.lock
  package.json
  src/app/screens/Dev/BrowseOfflineCache.tsx
  src/app/system/sync/fileCache.ts
  yarn.lock
Labels: Squash On Green

#410 feat: magical slide from left
  src/app/screens/Settings/navigation.tsx
Labels: Squash On Green

#403 feat(settings): Add new settings screen
  package.json
  src/app/App.tsx
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/app/screens/Settings/PresentationModeSettings.tsx
  src/app/screens/Settings/Settings.tsx
  src/app/screens/Settings/navigation.tsx
  src/app/system/sync/syncManager.ts
  src/palette/organisms/Screen/exposed/FullWidthDivider.tsx
  src/palette/organisms/Screen/index.tsx
  src/typings/reactNativeElipses.d.ts
  yarn.lock
Labels: Squash On Green

#416 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#417 feat(skeleton): Add skeleton loading states
  src/app/components/Skeleton.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artists/navigation.tsx
  src/app/system/store/Models/NetworkStatusModel.ts
  src/palette/organisms/Screen/exposed/LargeTitle.tsx
Labels: Jira Synced

#418 fix(polish): Increase touch area for settings / search icons
  src/app/Navigation.tsx
  src/app/components/Skeleton.tsx
  src/app/screens/HomeTabs.tsx
Labels: Jira Synced

#415 build: android CI, betas, RN upgrade
  .bundle/config
  .circleci/config.yml
  .editorconfig
  .gitattributes
  .gitignore
  .tool-versions
  Gemfile
  Gemfile.lock
  HACKS.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/energy/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/energy/MainActivity.java
  android/app/src/main/java/com/energy/MainApplication.java
  android/app/src/main/java/com/energy/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/com/energy/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/com/energy/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings.gradle
  app.json
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  ios/.xcode.env
  ios/Energy.xcodeproj/project.pbxproj
  ios/Energy/AppDelegate.m
  ios/Energy/AppDelegate.mm
  ios/Energy/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Energy/main.m
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/react-native+0.66.2.patch
  scripts/deploy-android
  scripts/deploy-both
  scripts/deploy-if-beta-branch-android
  scripts/distribute-android
  scripts/setup-distribute-linux
  scripts/setup-distribute-macos
  scripts/setup-fastlane-env
  src/app/screens/Auth/Login.tsx
  yarn.lock
Labels: Jira Synced

#422 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
