Repository artsy/energy, pull requests merged in 2022-11, with the labels that each got.

#289 feat: Add tabs to the Album screen
  src/app/navigation/Main.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumInstalls.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/HomeTabs/Albums/Albums.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/sharedUI/items/AlbumListItem.tsx
  src/app/sharedUI/screens/AddItemsToAlbum.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/sharedUI/screens/index.ts
  src/app/store/Models/AlbumsModel.tests.tsx
  src/app/store/Models/AlbumsModel.ts
  src/shared/utils/attemptAlbumMigration.ts
Labels: Jira Synced

#295 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#294 feat: display edition sets and update price logic
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Jira Synced

#290 feat: Search part 2 with pills
  src/app/screens/HomeTabs/Search/Search.tsx
  src/app/screens/HomeTabs/Search/SearchResult.tsx
Labels: Jira Synced

#217 fix: create album button avoids keyboard
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/sharedUI/molecules/ListEmptyComponent.tsx
Labels: Jira Synced, folio-bug-bash-1

#297 fix: headers messing up scrolling
  index.js
  src/app/screens/Dev/StorybookScreenAnimatedTitleHeader.tsx
  src/app/screens/Dev/StorybookScreenAnimatedTitleHeaderTabs.tsx
  src/app/sharedUI/screens/AddItemsToAlbum.tsx
  src/palette/organisms/Screen/hooks.ts
Labels: Jira Synced

#301 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#304 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#305 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#306 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#307 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#308 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#309 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#311 feat: Album document tab screen with new API
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
Labels: Jira Synced

#314 feat: select button on header
  src/app/screens/Auth/Login.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tests.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tests.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/items/DocumentGridItem.tsx
  src/app/sharedUI/screens/AddItemsToAlbum.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/Models/SelectModeModel.ts
  src/app/store/selectModeAtoms.ts
  src/palette/organisms/Screen/notExposed/ActualHeader.tsx
Labels: Jira Synced

#317 fix: return empty array is documentIDs is empty
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumDocuments.tsx
Labels: Squash On Green

#318 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#319 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#321 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#315 feat: install shots in albums and select mode
  src/ambient.d.ts
  src/app/navigation/Main.tsx
  src/app/navigation/navAtoms.ts
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumInstalls.tsx
  src/app/screens/HomeTabs/Albums/Albums.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tests.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/HomeTabs/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/HomeTabs/usePresentationFilteredArtworks.ts
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ArtworkImageGridItem.tsx
  src/app/sharedUI/items/DocumentGridItem.tsx
  src/app/sharedUI/screens/AddItemsToAlbum.tsx
  src/app/sharedUI/screens/Artwork/Artwork.tsx
  src/app/store/Models/AlbumsModel.tests.tsx
  src/app/store/Models/AlbumsModel.ts
  src/app/store/Models/SelectModeModel.ts
  src/app/store/selectModeAtoms.ts
  src/shared/utils/assertNever.ts
Labels: Jira Synced

#320 fix: show 2fa error when its wrong
  .env.example
  src/app/screens/Auth/Login.tsx
  src/app/store/Models/AuthModel.ts
Labels: Jira Synced

#312 fix : Artwork border box and About the artwork title should be hidden if artwork detail is empty
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Jira Synced

#324 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#325 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#326 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#327 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#329 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#330 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#331 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#332 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#333 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#334 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#335 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
