Repository artsy/energy, pull requests merged in 2022-08, with the labels that each got.

#129 fix: app crashes on clicking show
  src/__generated__/ShowsTabQuery.graphql.ts
  src/app/screens/HomeTabs/Shows/Shows.tests.tsx
  src/app/screens/HomeTabs/Shows/Shows.tsx
  src/app/sharedUI/molecules/ImagePlaceholder.tsx
Labels: Jira Synced

#132 feat: Add 2FA flow
  src/app/screens/Auth/Login.tsx
  src/app/store/Models/AuthModel.ts
Labels: Jira Synced

#135 feat: Presentation mode
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/HomeTabs/Settings/EditPresentationMode.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/sharedUI/molecules/SwitchContainer.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/Models/GlobalStoreModel.ts
  src/app/store/Models/PresenationModeModel.tsx
Labels: Jira Synced

#105 feat(MOPLAT-331): dark mode
  src/app/App.tsx
  src/app/AppProviders.tsx
  src/app/navigation/HomeTabsNavigationStack.tsx
  src/app/screens/Auth/Login.tsx
  src/app/screens/Dev/FolioDesignLanguage.tsx
  src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
  src/app/screens/HomeTabs/Albums/Albums.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/HomeTabs/HomeTabs.tsx
  src/app/screens/HomeTabs/Settings/DarkModeSettings.tsx
  src/app/screens/HomeTabs/Settings/Settings.tsx
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/items/ArtistListItem.tsx
  src/app/sharedUI/items/ArtworkGridItem.tsx
  src/app/sharedUI/items/ShowListItem.tsx
  src/app/sharedUI/molecules/SettingsItem.tsx
  src/app/sharedUI/molecules/index.ts
  src/app/sharedUI/screens/Artwork/AddArtworkToAlbum.tsx
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/store/Models/DevicePrefsModel.ts
  src/app/store/Models/GlobalStoreModel.ts
  src/app/wrappers/SuspenseWrapper.tsx
  src/app/wrappers/TabsContainer.tsx
  src/palette/Theme.tsx
  src/palette/atoms/BackButton/BackButton.tsx
  src/palette/elements/Avatar/Avatar.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/elements/Flex/Flex.tsx
  src/palette/elements/Input/Input.tsx
  src/palette/elements/Input/InputTitle.tsx
  src/palette/elements/Text/Text.tsx
  src/palette/elements/Touchable/Touchable.tsx
  src/palette/organisms/screenStructure/Screen.tsx
  src/palette/svgs/ArrowLeftIcon.tsx
  src/palette/svgs/ArrowRightIcon.tsx
  src/palette/svgs/BriefcaseIcon.tsx
  src/palette/svgs/ChevronIcon.tsx
  src/palette/svgs/EditIcon.tsx
  src/palette/svgs/HamburgerIcon.tsx
  src/palette/svgs/TrashIcon.tsx
Labels: Jira Synced, Squash On Green

#141 feat(MOPLAT-353): Show availability of artworks
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtworkGridItem_artwork.graphql.ts
  src/app/sharedUI/atoms/StatusDot.tsx
  src/app/sharedUI/atoms/index.ts
  src/app/sharedUI/index.ts
  src/app/sharedUI/items/ArtworkGridItem.tsx
Labels: Jira Synced

#144 feat: Show all Artwork details
  src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Jira Synced, Squash On Green

#148 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#150 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#145 WIP feat(MOPLAT-399): WebView back button is in wrong position
  src/app/sharedUI/screens/Artwork/ArtworkWebView.tsx
Labels: Jira Synced

#152 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#149 feat(MOPLAT-397): Add progress bar to CMS web view
  src/app/sharedUI/screens/Artwork/ArtworkWebView.tsx
Labels: Jira Synced

#156 feat(MOPLAT-397): Add progress bar to CMS web view
  src/app/sharedUI/screens/Artwork/ArtworkWebView.tsx
Labels: Jira Synced

#161 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#157 feat(MOPLAT-262): Install Shot QA
  src/app/sharedUI/Header.tsx
  src/app/sharedUI/screens/InstallImage/InstallImage.tsx
Labels: Jira Synced

#159 feat: Add more switches to Presentation mode
  src/app/screens/HomeTabs/Settings/EditPresentationMode.tsx
  src/app/store/Models/PresenationModeModel.tsx
Labels: Jira Synced

#155 feat: Splash screen
  android/app/src/main/java/com/energy/MainActivity.java
  android/app/src/main/res/drawable/launch_screen_dark.xml
  android/app/src/main/res/drawable/launch_screen_light.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/splash_icon_dark_theme.png
  android/app/src/main/res/mipmap-hdpi/splash_icon_light_theme.png
  android/app/src/main/res/mipmap-mdpi/splash_icon_dark_theme.png
  android/app/src/main/res/mipmap-mdpi/splash_icon_light_theme.png
  android/app/src/main/res/mipmap-xhdpi/splash_icon_dark_theme.png
  android/app/src/main/res/mipmap-xhdpi/splash_icon_light_theme.png
  android/app/src/main/res/mipmap-xxhdpi/splash_icon_dark_theme.png
  android/app/src/main/res/mipmap-xxhdpi/splash_icon_light_theme.png
  android/app/src/main/res/mipmap-xxxhdpi/splash_icon_dark_theme.png
  android/app/src/main/res/mipmap-xxxhdpi/splash_icon_light_theme.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/theme.xml
  ios/Energy/AppDelegate.m
  ios/Energy/Images.xcassets/Contents.json
  ios/Energy/Images.xcassets/SplashIcon.imageset/Contents.json
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 1x-1.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 1x-2.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 1x.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 2x-1.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 2x-2.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 2x.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 3x-1.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 3x-2.png
  ios/Energy/Images.xcassets/SplashIcon.imageset/Folio logo 3x.png
  ios/Energy/Info.plist
  ios/Energy/LaunchScreen.storyboard
  ios/Podfile.lock
  package.json
  src/app/App.tsx
  yarn.lock
Labels: Jira Synced

#158 fix: Login screen updates
  src/app/screens/Auth/Login.tsx
Labels: Jira Synced
