Repository artsy/energy, pull requests merged in 2023-01, with the labels that each got.

#424 fix: version/devmode toggle is back
  Gemfile.lock
  ios/Podfile.lock
  src/app/screens/Settings/Settings.tsx
Labels: Squash On Green

#425 feat: our own animated ellipsis
  package.json
  src/app/App.tsx
  src/app/components/AnimatedEllipsis.tsx
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/typings/reactNativeElipses.d.ts
  yarn.lock
Labels: Squash On Green

#430 fix: better spacing and colors for dark mode bottom sheet
  package.json
  src/app/components/BottomSheetModalView.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/palette/organisms/Screen/exposed/BottomView.tsx
  yarn.lock
Labels: Squash On Green

#432 feat: Add logout button on select partner screen
  src/app/screens/Auth/SelectPartner.tsx
Labels: Jira Synced

#429 feat(offline): Add retry support
  src/app/system/sync/syncManager.ts
  src/app/system/sync/utils/fetchOrCatch.ts
Labels: Jira Synced

#434 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#431 feat: with RetryErrorBoundary and fetchKeys
  src/app/Providers.tsx
  src/app/components/GlobalErrorView.tsx
  src/app/components/Items/AlbumListImage.tsx
  src/app/components/LoadFailureErrorView.tsx
  src/app/components/Tabs/TabScreen.tsx
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artists/navigation.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/EditArtworkInCms.tsx
  src/app/screens/Artwork/navigation.tsx
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/HomeTabs.tsx
  src/app/screens/Search/SearchResult.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/Shows/navigation.tsx
  src/app/system/relay/useSystemQueryLoader.ts
  src/app/system/store/Models/NetworkStatusModel.ts
  src/app/system/wrappers/ErrorBoundary.tsx
  src/app/system/wrappers/RetryErrorBoundary.tsx
Labels: Jira Synced

#437 fix: button styling and env switch working
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/system/store/Models/AuthModel.ts
Labels: Jira Synced

#435 test(offline): Add test coverage
  src/app/system/sync/__tests__/syncManager.tests.tsx
  src/app/system/sync/syncManager.ts
  src/app/system/sync/utils/__tests__/fetchOrCatch.tests.ts
Labels: Jira Synced, Squash On Green

#438 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#436 feat: select mode resets on appstart + general `sessionState` sanitize
  src/app/components/Items/ArtworkImageGridItem.tsx
  src/app/components/Items/DocumentGridItem.tsx
  src/app/screens/Albums/AddItemsToAlbum.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/system/store/GlobalStore.tsx
  src/app/system/store/Models/SelectModeModel.ts
  src/app/system/store/selectModeAtoms.ts
  src/app/utils/persistence.ts
Labels: Jira Synced

#447 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#440 feat: Sentry setup in energy
  .env.example
  .gitignore
  android/app/build.gradle
  fastlane/Fastfile
  ios/Podfile.lock
  package.json
  src/app/Navigation.tsx
  src/app/system/devTools/setupSentry.ts
  src/app/system/hooks/useErrorReporting.ts
  src/app/system/relay/middlewares/errorMiddleware.ts
  yarn.lock
Labels: Jira Synced

#450 fix: bottom button shadow and keyboard avoidance
  ios/Podfile.lock
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
Labels: Jira Synced

#451 feat: script to download sentry properties
  scripts/setup-env-for-artsy
  scripts/setup-sentry-properties
Labels: Jira Synced

#448 refactor(offline): Switch sync to use promise pooling and fine-grained progress % reporting
  package.json
  src/app/components/AnimatedEllipsis.tsx
  src/app/components/Items/DocumentGridItem.tsx
  src/app/system/sync/fileCache.ts
  src/app/system/sync/syncManager.ts
  yarn.lock
Labels: Squash On Green

#454 feat(staging): Add bottom border when in staging env
  src/app/Navigation.tsx
  src/palette/organisms/StatusBar.tsx
Labels: Jira Synced

#457 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#459 feat: android icons
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/build.gradle
Labels: Jira Synced

#456 chore: install sentry cli
  Gemfile.lock
  fastlane/Pluginfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#460 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#453 feat(ci): Add detect-secrets
  .secrets.baseline
  package.json
  scripts/detect-secrets.sh
Labels: Jira Synced

#458 feat: relay offline sync notice/detection
  .husky/pre-commit
  .husky/pre-push
  package.json
  scripts/relay-checksum.mjs
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/app/system/store/Models/GlobalStoreModel.ts
  src/app/system/sync/_generatedRelayChecksum.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#461 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#463 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#464 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#465 ci: change s3 access
  docs/environment_variables_configuration.md
  scripts/download-fonts
  scripts/prepare-env-vars
  scripts/setup-distribute-linux
  scripts/setup-distribute-macos
  scripts/setup-env-for-ci
  scripts/setup-sentry-properties
Labels: Jira Synced

#467 fix: small fixes and additions after demo days prep
  android/app/build.gradle
  ios/Energy.xcodeproj/xcshareddata/xcschemes/Energy (Store).xcscheme
  ios/Podfile.lock
  package.json
  src/app/Navigation.tsx
  src/app/screens/Dev/BrowseOfflineCache.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/app/screens/Settings/Settings.tsx
  src/app/system/store/Models/DevicePrefsModel.ts
  src/app/system/sync/fileCache.ts
  src/app/system/sync/syncManager.ts
  yarn.lock
Labels: Squash On Green

#466 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#468 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#469 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#470 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#471 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#472 fix: leave some space before the ellipsis
  src/app/screens/Settings/OfflineModeSettings.tsx
Labels: Squash On Green

#473 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#474 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#475 fix: android crash
  Gemfile.lock
  src/app/system/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced, Squash On Green

#477 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#478 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#481 feat: remove old comment
  src/app/system/store/Models/EnvironmentModel.ts
Labels: Squash On Green

#480 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#483 fix(folio-release): Fix screen flash and clear cache when logged out
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/app/screens/Settings/Settings.tsx
  src/app/system/store/Models/AuthModel.ts
  src/app/system/store/Models/DevicePrefsModel.ts
  src/app/system/store/Models/GlobalStoreModel.ts
  src/palette/organisms/Screen/atoms.ts
Labels: Jira Synced
