Repository artsy/energy, pull requests merged in 2023-03, with the labels that each got.

#537 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#538 chore(jest): upgrade jest@28
  package.json
  src/setupJest.ts
  yarn.lock
Labels: Squash On Green

#540 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#536 refactor(select-mode): Refactor select mode app-wide and simplify album management
  src/app/components/BottomSheetModalView.tsx
  src/app/components/FileTypeIcon.tsx
  src/app/components/Items/AlbumListImage.tsx
  src/app/components/Items/AlbumListItem.tsx
  src/app/components/Items/ArtworkGridItem.tsx
  src/app/components/Items/__tests__/AlbumListImage.tests.tsx
  src/app/components/SelectMode.tsx
  src/app/components/__tests__/SelectMode.tests.tsx
  src/app/screens/Albums/AddItemsToAlbum.tsx
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/Albums/AlbumTabs/AlbumInstalls.tsx
  src/app/screens/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/Albums/AlbumTabs/__tests__/AlbumDocuments.tests.tsx
  src/app/screens/Albums/AlbumTabs/__tests__/AlbumTabs.tests.tsx
  src/app/screens/Albums/Albums.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/Albums/CreateOrEditAlbum/useArtworksByMode.ts
  src/app/screens/Albums/navigation.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/Artists/ArtistTabs/ArtistShows/ArtistShows.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/useMailComposer.ts
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/Shows/Shows.tsx
  src/app/system/devTools/ignoreLogs.ts
  src/app/system/hooks/useSystemIsDoneBooting.ts
  src/app/system/store/Models/AlbumsModel.tests.tsx
  src/app/system/store/Models/AlbumsModel.ts
  src/app/system/store/Models/GlobalStoreModel.ts
  src/app/system/store/Models/NetworkStatusModel.ts
  src/app/system/store/Models/SelectModeModel.ts
  src/app/system/store/Models/__tests__/AlbumsModel.tests.tsx
  src/app/system/store/Models/__tests__/SelectModeModel.tests.ts
  src/app/system/store/migrations.ts
  src/app/system/store/persistence/migrateState.ts
  src/app/system/sync/_generatedRelayChecksum.ts
  src/app/system/sync/syncManager.ts
  src/app/utils/attemptAlbumMigration.ts
  src/app/utils/getContentContainerStyle.ts
  src/setupJest.ts
Labels: Jira Synced

#541 chore: update metaphysics graphql schema
  src/app/system/sync/_generatedRelayChecksum.ts
Labels: Squash On Green

#542 chore(stuff): Fix bugs and add new email setting functionality
  ios/Podfile.lock
  package.json
  src/app/components/BottomSheetModalView.tsx
  src/app/components/Items/ArtworkGridItem.tsx
  src/app/components/ScrollableScreensView/ScrollableLazyScreen.tsx
  src/app/components/ScrollableScreensView/ScrollableScreensContext.ts
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumTabs.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/screens/Artwork/__tests__/useMailComposer.tests.ts
  src/app/screens/Artwork/navigation.tsx
  src/app/screens/Artwork/useMailComposer.ts
  src/app/screens/Settings/EmailScreen.tsx
  src/app/screens/Settings/MultipleArtworksAndArtists.tsx
  src/app/screens/Settings/MultipleArtworksBySameArtist.tsx
  src/app/screens/Settings/OneArtwork.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/system/devTools/ignoreLogs.ts
  src/app/system/store/Models/EmailModel.ts
  src/app/system/store/migrations.ts
  src/app/system/sync/__tests__/syncManager.tests.tsx
  src/app/system/sync/_generatedRelayChecksum.ts
  src/app/system/sync/syncManager.ts
  src/app/system/wrappers/CachedImage.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#543 chore(perf): Wrap flatlist renders in useCallback
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/Artists.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
Labels: Squash On Green

#544 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#549 chore: update metaphysics graphql schema
  src/app/system/sync/_generatedRelayChecksum.ts
Labels: Squash On Green

#557 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#558 fix(bugs): Fix Android dark mode and max-width on titles
  android/app/src/main/res/values/styles.xml
  package.json
  src/Providers.tsx
  src/components/Screen/notExposed/ActualHeader.tsx
  src/screens/Settings/DarkModeSettings.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#560 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#561 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#562 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#564 feat(animation): Add animation polish
  .eslintrc.js
  HACKS.md
  src/components/AnimatedEllipsis.tsx
  src/components/BottomSheet/BottomSheetActions.tsx
  src/components/BottomSheet/BottomSheetModalView.tsx
  src/components/Items/ArtworkGridItem.tsx
  src/components/Lists/ArtworksList.tsx
  src/components/Lists/DocumentList.tsx
  src/components/Lists/InstallationsList.tsx
  src/components/Portal.tsx
  src/components/Screen/Body.tsx
  src/components/Screen/BottomView.tsx
  src/components/Screen/Header.tsx
  src/components/Screen/constants.ts
  src/components/SelectMode.tsx
  src/components/Tabs/TabsWithHeader.tsx
  src/components/Tabs/useListenForTabContentScroll.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastContext.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/AlbumTabs/AlbumListItem.tsx
  src/screens/Albums/Albums.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/screens/Albums/useValidateAlbumItems.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Artwork/useMailComposer.ts
  src/screens/Auth/Login.tsx
  src/screens/HomeTabs.tsx
  src/screens/Search/Search.tsx
  src/screens/Search/SearchFilters.tsx
  src/screens/Search/SearchResult.tsx
  src/screens/Settings/OfflineModeSettings.tsx
  src/system/hooks/useNetworkStatusListener.ts
  src/system/relay/useSystemFetchQuery.ts
  src/utils/hooks/animations/useFadeInAnimation.ts
  src/utils/hooks/animations/useSlideUpFromBottomAnimation.ts
  src/utils/waitForScreenTransition.ts
Labels: Squash On Green

#567 refactor(offline): Remove jotai state
  .husky/pre-push
  package.json
  scripts/relay-checksum.mjs
  src/Navigation.tsx
  src/components/Items/ArtistListItem.tsx
  src/components/Items/DocumentGridItem.tsx
  src/screens/Settings/OfflineModeSettings.tsx
  src/screens/Shows/Shows.tsx
  src/system/store/Models/DevicePrefsModel.ts
  src/system/sync/artifacts/__generatedRelayChecksum.ts
  src/system/sync/fileCache.ts
  src/system/sync/fileCache/clearFileCache.ts
  src/system/sync/fileCache/constants.ts
  src/system/sync/fileCache/downloadFile.ts
  src/system/sync/fileCache/getFile.ts
  src/system/sync/fileCache/getFilePath.ts
  src/system/sync/fileCache/index.ts
  src/system/sync/fileCache/initializeFS.ts
  src/system/sync/fileCache/saveFile.ts
  src/system/sync/fileCache/urlMap.ts
  src/system/sync/fileCache/useLocalUri.ts
  src/system/sync/syncManager.ts
  src/system/wrappers/CachedImage.tsx
  src/typings/assertNever.d.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#569 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#571 feat(offline): Add more robust file download retries
  src/components/Items/DocumentGridItem.tsx
  src/system/relay/middlewares/errorMiddleware.ts
  src/system/sync/__tests__/retryOperation.tests.tsx
  src/system/sync/__tests__/syncManager.tests.tsx
  src/system/sync/fileCache/__tests__/clearFileCache.tests.ts
  src/system/sync/fileCache/__tests__/getFileFromCache.tests.ts
  src/system/sync/fileCache/__tests__/getFilePath.tests.ts
  src/system/sync/fileCache/__tests__/saveFileToCache.tests.ts
  src/system/sync/fileCache/__tests__/urlMap.tests.ts
  src/system/sync/fileCache/__tests__/warmFilesystem.tests.ts
  src/system/sync/fileCache/downloadFileToCache.ts
  src/system/sync/fileCache/getFileFromCache.ts
  src/system/sync/fileCache/index.ts
  src/system/sync/fileCache/saveFileToCache.ts
  src/system/sync/fileCache/warmFilesystem.ts
  src/system/sync/retryOperation.ts
  src/system/sync/syncManager.ts
Labels: Jira Synced

#573 temp(debugging): Add offline developer debug tooling
  package.json
  src/screens/Settings/OfflineModeSettings.tsx
  src/system/sync/__tests__/syncManager.tests.tsx
  src/system/sync/fileCache/downloadFileToCache.ts
  src/system/sync/syncManager.ts
  yarn.lock
Labels: Squash On Green

#574 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#575 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#576 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#580 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#582 fix(MOPLAT-676): Hides artwork count on presentation mode
  src/components/Items/ArtistListItem.tsx
Labels: Jira Synced

#584 fix: requests hitting wrong environment after switching
  src/system/relay/middlewares/checkAuthenticationMiddleware.ts
  src/system/relay/middlewares/metaphysicsUrlMiddleware.ts
Labels: Jira Synced
