Repository artsy/energy, pull requests merged in 2023-11, with the labels that each got.

#754 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#755 build(deps): clean up and reorder deps
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#756 build(deps): bumps react-native-keep-awake from 1.1.0 to 1.2.2
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#731 chore: use m1 machines in ci
  .circleci/config.yml
Labels: Jira Synced

#758 build(deps): bump important deps
  .circleci/config.yml
  .nvmrc
  .tool-versions
  Gemfile
  Gemfile.lock
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#763 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#759 build(deps): bump react-native from 0.69.12 to 0.70.13
  .circleci/config.yml
  .gitignore
  Gemfile
  Gemfile.lock
  HACKS.md
  android/app/build.gradle
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  ios/Energy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/@react-native-community+cli-platform-ios+9.3.0.patch
  yarn.lock
Labels: Jira Synced

#764 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#765 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#766 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#768 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#769 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#770 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#761 build(deps): Replaces expo and expo-mail-composer and uses react-native-mail instead
  HACKS.md
  android/app/src/main/java/com/energy/MainActivity.java
  android/app/src/main/java/com/energy/MainApplication.java
  android/build.gradle
  android/settings.gradle
  ios/Energy.xcodeproj/project.pbxproj
  ios/Energy/AppDelegate.h
  ios/Energy/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  package.json
  src/screens/Artwork/__tests__/useMailComposer.tests.ts
  src/screens/Artwork/useMailComposer.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#771 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#772 feat(tests): tests for mailCompooser
  src/screens/Artwork/useMailComposer.tests.ts
  src/screens/Artwork/useMailComposer.ts
  src/setupJest.ts
Labels: ff

#774 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#775 fix(ci): beta failures
  fastlane/Fastfile
  ios/Energy.xcodeproj/project.pbxproj
  package.json
  scripts/setup-env-for-ci
Labels: Jira Synced

#776 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#777 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#773 feat(build): Enables hermes
  android/app/build.gradle
  android/app/proguard-rules.pro
  babel.config.js
  fastlane/Fastfile
  index.js
  ios/Energy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  scripts/hermes/hermes-android-bundle-bytecode.sh
  scripts/hermes/hermes-android-bundle.sh
  scripts/hermes/hermes-android-sourcemap.sh
  scripts/hermes/hermes-ios-bundle-bytecode.sh
  scripts/hermes/hermes-ios-bundle-sourcemap.sh
  scripts/hermes/hermes-ios-bundle.sh
  yarn.lock
Labels: Jira Synced

#779 feat: bring back reanimated update
  .circleci/config.yml
  HACKS.md
  android/app/src/main/java/com/energy/MainApplication.java
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+3.3.0.patch
  src/Providers.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#780 build(deps): bump @sentry/react-native from 4.12.0 to 5.14.1
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  src/system/devTools/setupSentry.ts
  yarn.lock
Labels: Jira Synced

#781 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
