Repository artsy/energy, pull requests merged in 2023-05, with the labels that each got.

#611 chore(eslint-jsx): Add rule to guard against leaked renders
  .eslintrc.js
Labels: Squash On Green

#612 fix(offline): Don't show dev mode settings if not dev
  .eslintrc.js
  jest.config.js
  package.json
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSync.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#614 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#613 feat(palette-mobile): Point <Screen /> at palette-mobile
  package.json
  src/Navigation.tsx
  src/Providers.tsx
  src/components/BottomSheet/BottomSheetModalView.tsx
  src/components/LoadFailureErrorView.tsx
  src/components/Screen/BottomView.tsx
  src/components/Screen/FullWidthDivider.tsx
  src/components/SettingsItem.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/Albums.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtist.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/screens/Artwork/ArtworkWebView.tsx
  src/screens/Auth/Login.tsx
  src/screens/Auth/SelectPartner.tsx
  src/screens/Search/Search.tsx
  src/screens/Settings/DarkModeSettings.tsx
  src/screens/Settings/Email/EmailSettings.tsx
  src/screens/Settings/Email/MultipleArtworksAndArtists.tsx
  src/screens/Settings/Email/MultipleArtworksBySameArtist.tsx
  src/screens/Settings/Email/OneArtwork.tsx
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSync.tsx
  src/screens/Settings/PresentationModeSettings.tsx
  src/screens/Settings/Settings.tsx
  src/utils/hooks/useIsDarkMode.ts
  yarn.lock
Labels: Jira Synced

#616 fix: update palette for reanimated crashes again #trivial
  package.json
  yarn.lock
Labels: Squash On Green

#617 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#619 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#610 build(deps): upgrades reanimated to 3.0.2
  .circleci/config.yml
  android/app/src/main/java/com/energy/MainApplication.java
  ios/Podfile.lock
  package.json
  src/components/Tabs/TabsScrollView.tsx
  src/screens/Albums/Albums.tsx
  yarn.lock
Labels: Jira Synced

#626 refactor(offline): If image already downloaded, skip downloading it again
  package.json
  src/components/Items/DocumentGridItem.tsx
  src/components/Tabs/TabsWithHeader.tsx
  src/system/hooks/useNetworkStatusListener.ts
  src/system/store/Models/NetworkStatusModel.ts
  src/system/sync/components/OfflineLoadingWrapper.tsx
  src/system/sync/fileCache/downloadFileToCache.ts
  src/system/sync/syncManager.ts
  yarn.lock
Labels: Jira Synced

#630 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#631 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#632 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#633 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#634 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#635 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#636 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#637 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#640 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#641 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#642 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
