Repository artsy/energy, pull requests merged in 2023-02, with the labels that each got.

#484 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#485 fix(android-keyboard): Use default KeyboardAvoidingView
  src/app/components/ArtsyKeyboardAvoidingView.tsx
  src/palette/organisms/Screen/exposed/Body.tsx
Labels: Jira Synced

#486 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#487 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#488 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#490 fix(release): Address more release bug / feature items
  ios/Podfile.lock
  src/app/components/Items/AlbumListImage.tsx
  src/app/components/Items/ArtworkGridItem.tsx
  src/app/components/Items/__tests__/AlbumListImage.tests.tsx
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/Albums/AlbumTabs/__tests__/AlbumDocuments.tests.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/Artists.tsx
  src/app/screens/Artwork/Artwork.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/system/relay/useSystemFetchQuery.ts
  src/app/system/store/Models/AlbumsModel.tests.tsx
  src/app/system/store/Models/AlbumsModel.ts
  src/app/utils/test/setupTestWrapper.tsx
Labels: Jira Synced

#493 feat: env var obfuscation
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#495 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#498 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#497 feat(migrations): Add state migrations
  dangerfile.ts
  ios/Podfile.lock
  package.json
  src/app/App.tsx
  src/app/Navigation.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
  src/app/system/devTools/AsyncStorageDevtools.tsx
  src/app/system/devTools/setupSentry.ts
  src/app/system/hooks/useSystemIsDoneBooting.ts
  src/app/system/store/GlobalStore.tsx
  src/app/system/store/Models/GlobalStoreModel.ts
  src/app/system/store/migrations.ts
  src/app/system/store/persistence/__tests__/migrateState.tests.ts
  src/app/system/store/persistence/migrateState.ts
  src/app/system/store/persistence/sanitize.ts
  src/app/system/store/persistence/storageAdapter.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#501 fix(android): Use SVG for android splash screen
  android/app/src/main/res/drawable/launch_screen_dark.xml
  android/app/src/main/res/drawable/launch_screen_light.xml
  android/app/src/main/res/drawable/logo_dark.xml
  android/app/src/main/res/drawable/logo_light.xml
Labels: Jira Synced, Squash On Green

#502 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#503 feat: upgrade palette, remove react-spring, fix value type-checks
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  src/app/Providers.tsx
  src/app/components/BottomSheetModalView.tsx
  src/app/components/ImageModal.tsx
  src/app/components/ImagePlaceholder.tsx
  src/app/components/Items/AlbumListItem.tsx
  src/app/components/Items/ShowListItem.tsx
  src/app/components/ListEmptyComponent.tsx
  src/app/components/LoadFailureErrorView.tsx
  src/app/components/SettingsItem.tsx
  src/app/screens/Albums/AddItemsToAlbum.tsx
  src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
  src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
  src/app/screens/Albums/Albums.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
  src/app/screens/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
  src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/app/screens/Artists/Artists.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/app/screens/Auth/Login.tsx
  src/app/screens/Auth/SelectPartner.tsx
  src/app/screens/Dev/DevMenu.tsx
  src/app/screens/Settings/OfflineModeSettings.tsx
  src/app/screens/Settings/OneArtwork.tsx
  src/app/screens/Settings/Settings.tsx
  src/app/screens/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
  src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
  src/app/screens/Shows/ShowTabs/ShowInstalls/ShowInstalls.tsx
  src/app/screens/Shows/ShowTabs/ShowTabs.tsx
  src/app/screens/Shows/Shows.tsx
  src/app/utils/renderMarkdown.tsx
  src/palette/organisms/Screen/exposed/Body.tsx
  src/palette/organisms/Screen/exposed/BottomView.tsx
  src/palette/organisms/Screen/exposed/FloatingHeader.tsx
  src/palette/organisms/Screen/exposed/FullWidthItem.tsx
  src/palette/organisms/Screen/exposed/LargeTitle.tsx
  yarn.lock
Labels: Squash On Green

#505 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#506 lib(offline): Bump promise-pool with latest API
  package.json
  src/app/system/sync/syncManager.ts
  yarn.lock
Labels: Squash On Green

#507 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#508 fix: rename app to Folio on Android #trivial
  android/app/src/main/res/values/strings.xml
  app.json
Labels: Jira Synced, Squash On Green

#509 fix: login button
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#510 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#511 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#513 fix(offline): Fix mysterious sync crash on device
  src/app/system/sync/syncManager.ts
Labels: Jira Synced

#512 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#514 fix: sentry sourcemaps + bundled js upload
  .gitignore
  dist/.gitkeep
  fastlane/Fastfile
  package.json
Labels: Squash On Green

#516 fix(crash): don't restore view state to prevent crash in fragment
  android/app/src/main/java/com/energy/MainActivity.java
Labels: Squash On Green

#517 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#519 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#521 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#518 fix: loading button spinner
  package.json
  src/app/Providers.tsx
  src/app/components/Items/AlbumListItem.tsx
  src/app/screens/Artwork/ArtworkContent/ArtworkDetail.tsx
  src/palette/organisms/Screen/exposed/FullWidthItem.tsx
  yarn.lock
Labels: Squash On Green

#522 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#523 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#524 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#525 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#526 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#527 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#528 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#532 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#534 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
