Repository artsy/energy, pull requests merged in 2023-04, with the labels that each got.

#586 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#587 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#589 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#590 fix(log-in): Return all partner results on login
  data/schema.graphql
  src/screens/Auth/SelectPartner.tsx
Labels: Jira Synced

#592 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#588 feat: offline improvements
  ios/Podfile.lock
  package.json
  src/components/Tabs/TabScreen.tsx
  src/screens/Settings/OfflineModeSettings.tsx
  src/setupJest.ts
  src/system/hooks/useNetworkStatusListener.ts
  src/system/sync/components/OfflineLoadingWrapper.tsx
  src/system/sync/syncManager.ts
  src/typings/mockRNCNetInfo.d.ts
  yarn.lock
Labels: Jira Synced

#591 fix(webview): Fix webview crashes on Android
  docs/developing_local_palette.md
  package.json
  src/Navigation.tsx
  src/screens/Artwork/ArtworkWebView.tsx
  src/utils/hooks/useWebViewCookies.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#593 fix: make installs more defensive
  src/screens/Albums/AlbumTabs/AlbumInstalls.tsx
  src/screens/Shows/ShowTabs/ShowInstalls.tsx
Labels: Jira Synced

#594 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#596 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#597 chore: specify new mac resource in config
  .circleci/config.yml
Labels: Jira Synced, Squash On Green

#598 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#599 feat(offline): Add new offline sync screen
  package.json
  src/components/AnimatedEllipsis.tsx
  src/components/Screen/Header.tsx
  src/components/Screen/index.tsx
  src/components/Tabs/TabsWithHeader.tsx
  src/components/Tabs/useListenForTabContentScroll.tsx
  src/screens/Settings/DarkModeSettings.tsx
  src/screens/Settings/Email/EmailSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSync.tsx
  src/screens/Settings/OfflineModeSettings.tsx
  src/screens/Settings/PresentationModeSettings.tsx
  src/screens/Settings/navigation.tsx
  src/system/sync/__tests__/syncManager.tests.tsx
  src/system/sync/syncManager.ts
  src/utils/delay.ts
  yarn.lock
Labels: Jira Synced

#601 refactor(persisted-state): use easy-peasy persisted state migration support
  package.json
  src/system/hooks/useSystemIsDoneBooting.ts
  src/system/store/GlobalStore.tsx
  src/system/store/Models/GlobalStoreModel.ts
  src/system/store/Models/SystemModel.ts
  src/system/store/migrations.ts
  src/system/store/persistence/__tests__/migrateState.tests.ts
  src/system/store/persistence/migrateState.ts
  yarn.lock
Labels: Jira Synced

#602 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#603 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#604 fix: navigation bar color
  src/Navigation.tsx
  src/screens/Settings/DarkModeSettings.tsx
  src/utils/hooks/useAndroidNavigationBarThemeListener.ts
Labels: Jira Synced

#606 chore: remove release check in circle
  .circleci/config.yml
Labels: Squash On Green

#608 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#609 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
