Repository artsy/energy, pull requests merged in 2023-12, with the labels that each got.

#784 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#785 feat: add flip table scripts (┛✧Д✧))┛彡┻━┻
  package.json
  scripts/utils/flip-table
  scripts/utils/flip-table-extreme
Labels: Squash On Green, ff

#786 chore(scripts): Make flip table executable
  scripts/utils/flip-table
  scripts/utils/flip-table-extreme
Labels: Squash On Green

#788 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#789 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#790 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#791 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#792 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#793 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#795 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#794 build(codepush): codepush sdk integration
  .env.example
  .gitignore
  HACKS.md
  android/app/build.gradle
  android/app/src/main/java/com/energy/MainApplication.java
  android/app/src/main/java/com/energy/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  ios/Energy/AppDelegate.mm
  ios/Podfile.lock
  package.json
  patches/react-native-code-push+7.1.0.patch
  scripts/setup/download-assets-android
  scripts/setup/download-assets-ios
  src/App.tsx
  src/system/codepush.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#796 build(codepush): codepush dev menu
  src/screens/Settings/DevMenu/CodePushOptions.tsx
  src/screens/Settings/DevMenu/DevMenu.tsx
  src/screens/Settings/Settings.tsx
Labels: Jira Synced, Squash On Green

#799 fix(codepush): codepush ci sentry follow ups
  .circleci/config.yml
  .gitignore
  Gemfile.lock
  app.json
  docs/deploy_a_hotfix.md
  docs/using_codepush.md
  fastlane/Pluginfile
  fastlane/sentry_fastlane.rb
  fastlane/utility_fastlane.rb
  scripts/codepush/determine-deployment-type.sh
  scripts/codepush/maybe_notify_beta_needed.sh
  src/system/devTools/sentrySetup.ts
  src/system/hooks/useErrorReporting.ts
  src/utils/jsonFiles.ts
Labels: Jira Synced, Squash On Green

#800 chore: analytics init
  .circleci/config.yml
  .vscode/settings.json
  android/app/src/main/AndroidManifest.xml
  babel.config.js
  ios/Energy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  scripts/ci/build-for-tests-android
  src/App.tsx
  src/Providers.tsx
  src/ambient.d.ts
  src/utils/track/SegmentTrackingProvider.ts
  src/utils/track/index.tsx
  src/utils/track/providers.tsx
  tsconfig.json
  yarn.lock
Labels: Jira Synced, Squash On Green
