Repository artsy/energy, pull requests merged in 2024-01, with the labels that each got.

#801 feat: android email images as pdf
  ios/Podfile.lock
  package.json
  src/screens/Artwork/useMailComposer.tests.ts
  src/screens/Artwork/useMailComposer.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, ff

#802 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#803 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#805 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#806 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#807 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#809 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#810 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#811 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#812 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#813 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#814 fix: email statuses
  src/screens/Artwork/useMailComposer.ts
Labels: ff

#816 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#817 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#819 fix(email): Update email message
  scripts/utils/flip-table-light.sh
  src/components/BottomSheet/BottomSheetActions.tsx
  src/screens/Artwork/Artwork.tsx
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useMailComposer.ts
Labels: Jira Synced

#820 feat(email): Artwork images are linkable
  jest.config.js
  package.json
  src/App.tsx
  src/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useMailComposer.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#822 feat(orientation): Add support for landscape mode
  android/app/src/main/AndroidManifest.xml
  ios/Energy/Info.plist
Labels: Jira Synced, Squash On Green

#825 fix(albums): Always show add works album
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
Labels: Jira Synced

#827 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#829 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#831 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#832 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#833 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#834 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#826 feat(app): Add pull to refresh
  .circleci/config.yml
  Gemfile.lock
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+3.3.0.patch
  src/components/ArtworkImageModal.tsx
  src/components/Lists/ArtistsList.tsx
  src/components/Lists/ShowsList.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/screens/Artists/ArtistTabs/ArtistArtworks.tsx
  src/screens/Artists/ArtistTabs/ArtistDocuments.tsx
  src/screens/Artists/ArtistTabs/ArtistShows.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Artwork/EditArtworkInCms.tsx
  src/screens/Auth/SelectPartner.tsx
  src/screens/Search/SearchResult.tsx
  src/screens/Shows/ShowTabs/ShowArtworks.tsx
  src/screens/Shows/ShowTabs/ShowDocuments.tsx
  src/screens/Shows/ShowTabs/ShowInstalls.tsx
  src/screens/Shows/ShowTabs/ShowTabs.tsx
  src/screens/Shows/Shows.tsx
  src/system/relay/useSystemFetchQuery.ts
  src/system/relay/useSystemQueryLoader.ts
  src/system/relay/useSystemQueryLoader.tsx
  src/utils/hooks/useUpdateEffect.ts
  yarn.lock
Labels: Jira Synced

#835 build(codepush): make fastlane message for native code more descriptive
  fastlane/utility_fastlane.rb
Labels: Squash On Green

#836 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#838 fix: album migration issues
  .secrets.baseline
  ios/NativeModules/ARTAlbumMigrationModule.m
  src/screens/Auth/Login.tsx
  src/screens/Settings/DevMenu/DevMenu.tsx
  src/utils/__tests__/attemptAlbumMigrations.tests.ts
  src/utils/attemptAlbumMigration.ts
Labels: Jira Synced

#839 chore(danger): Guard against useRelayEnvironment import via Danger
  dangerfile.ts
Labels: Squash On Green

#840 chore(qa): Misc QA updates
  package.json
  scripts/utils/flip-table-light
  src/App.tsx
  src/Boot.tsx
  src/Navigation.tsx
  src/components/Animations/FadeIn.tsx
  src/components/Items/ArtistListItem.tsx
  src/components/Items/ShowListItem.tsx
  src/components/ProgressBar.tsx
  src/components/SettingsItem.tsx
  src/components/StatusBar.tsx
  src/screens/Albums/AlbumTabs/AlbumListItem.tsx
  src/screens/Albums/Albums.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/__tests__/useAlbum.tests.tsx
  src/screens/Auth/Login.tsx
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSync.tsx
  src/screens/Settings/PresentationModeSettings.tsx
  src/system/analytics/trackSegmentEvent.ts
  src/system/hooks/__tests__/useNavigationHistory.tests.tsx
  src/system/hooks/useTrackScreen.ts
  src/system/store/Models/AuthModel.ts
  src/system/store/Models/DevicePrefsModel.ts
  src/system/sync/syncManager.ts
  src/system/sync/utils/__tests__/fetchOrCatch.tests.ts
  src/system/sync/utils/fetchOrCatch.ts
  src/system/wrappers/ThemeProvider.tsx
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useIsScreenVisible.ts
  src/utils/hooks/useMailComposer.ts
  src/utils/test/renderWithWrappers.tsx
Labels: Jira Synced

#841 fix(offline): Ensure we don't write store to disk after a cancel
  src/components/Items/ShowListItem.tsx
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/screens/Settings/OfflineMode/OfflineModeSync.tsx
  src/system/store/Models/AuthModel.ts
  src/system/store/Models/DevicePrefsModel.ts
  src/system/sync/__tests__/syncManager.tests.tsx
  src/system/sync/fileCache/__tests__/clearFileCache.tests.ts
  src/system/sync/fileCache/__tests__/getCurrentSyncProgress.tests.ts
  src/system/sync/fileCache/__tests__/getFilePath.tests.ts
  src/system/sync/fileCache/__tests__/warmFilesystem.tests.ts
  src/system/sync/fileCache/clearFileCache.ts
  src/system/sync/fileCache/constants.ts
  src/system/sync/fileCache/getCurrentSyncProgress.ts
  src/system/sync/fileCache/getFilePath.ts
  src/system/sync/fileCache/warmFilesystem.ts
  src/system/sync/syncManager.ts
Labels: Squash On Green

#842 chore(syncManager): Cancel promise pool if sync aborted
  src/components/SelectMode.tsx
  src/screens/Settings/OfflineMode/OfflineModeSettings.tsx
  src/system/sync/__tests__/retryOperation.tests.tsx
  src/system/sync/retryOperation.ts
  src/system/sync/syncManager.ts
Labels: Squash On Green

#844 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#845 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#847 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#848 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#849 refactor(email): Update send email template
  src/components/Items/ArtistListItem.tsx
  src/screens/Auth/SelectPartner.tsx
  src/system/store/Models/AuthModel.ts
  src/system/sync/components/OfflineLoadingWrapper.tsx
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useMailComposer.ts
Labels: Squash On Green

#850 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#851 feat(email): Add link to partner in email
  package.json
  src/screens/Auth/SelectPartner.tsx
  src/system/hooks/useNetworkStatusListener.ts
  src/system/store/Models/AuthModel.ts
  src/system/sync/components/OfflineLoadingWrapper.tsx
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useMailComposer.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#853 chore: remove dead code
  src/components/MeasuredView.tsx
  src/components/Wrap.tsx
Labels: Squash On Green

#854 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#855 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
