Repository artsy/energy, pull requests merged in 2024-02, with the labels that each got.

#858 fix(email): Hide price if presentation mode setting is on
  src/utils/hooks/__tests__/useMailComposer.tests.ts
  src/utils/hooks/useMailComposer.ts
Labels: Squash On Green

#859 fix: broken sentry sourcemaps
  .circleci/config.yml
  fastlane/sentry_fastlane.rb
  package.json
  yarn.lock
Labels: Jira Synced

#860 feat: add perf monitoring flipper tool
  android/app/src/debug/java/com/energy/ReactNativeFlipper.java
  ios/Energy/AppDelegate.mm
  ios/Podfile.lock
  package.json
  src/components/Lists/ArtistsList.tsx
  yarn.lock
Labels: Jira Synced

#862 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#861 perf(artistlists): boost performance of big partner lists
  src/components/Lists/ArtistsList.tsx
  src/system/sync/artifacts/__generatedRelayChecksum.ts
Labels: Jira Synced

#863 chore(performance): Add native stack screens, other perf items
  package.json
  src/App.tsx
  src/Navigation.tsx
  src/components/BottomSheet/BottomSheetModalView.tsx
  src/components/Lists/ArtistsList.tsx
  src/components/Lists/ArtworksList.tsx
  src/screens/Albums/AlbumTabs/AlbumListItem.tsx
  src/screens/Albums/AlbumTabs/__tests__/AlbumListItem.tests.tsx
  src/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/screens/Search/Search.tsx
  src/system/store/Models/PresentationModeModel.tsx
  src/utils/hooks/useIsMounted.ts
  yarn.lock
Labels: Squash On Green

#864 fix(select-mode): Fix select mode; improve animation of select mode
  src/components/Items/ArtworkGridItem.tsx
  src/components/Items/ShowListItem.tsx
  src/components/Lists/ArtworksList.tsx
  src/components/Lists/ShowsList.tsx
  src/components/SelectMode.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Auth/Login.tsx
  src/screens/HomeTabs.tsx
  src/screens/Search/Search.tsx
  src/screens/Search/SearchContext.tsx
  src/screens/Shows/Shows.tests.tsx
  src/system/analytics/initializeSegment.ts
  src/system/sync/artifacts/__generatedRelayChecksum.ts
Labels: Squash On Green

#867 fix(shows): Add preloader state
  package.json
  src/components/SelectMode.tsx
  src/components/SelectModePortal.tsx
  src/components/TabsView.tsx
  src/components/__tests__/SelectMode.tests.tsx
  src/screens/Artists/ArtistTabs/ArtistShows.tsx
  src/screens/Shows/ShowTabs/ShowArtworks.tsx
  src/screens/Shows/ShowTabs/ShowTabs.tsx
  src/system/relay/useSystemQueryLoader.tsx
  yarn.lock
Labels: Squash On Green

#868 fix(artwork): Guard against missing markdown text
  package.json
  src/utils/flattenChildren.ts
  src/utils/renderMarkdown.tsx
  yarn.lock
Labels: Jira Synced

#869 refactor(select-mode): Refactor select mode action implementation
  src/components/Lists/ArtworksList.tsx
  src/components/Lists/DocumentList.tsx
  src/components/Lists/InstallationsList.tsx
  src/components/Portal.tsx
  src/components/SelectMode/SelectMode.tsx
  src/components/SelectMode/SelectModeActions.tsx
  src/components/SelectModePortal.tsx
  src/components/TabsView.tsx
  src/components/__tests__/SelectMode.tests.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/screens/Albums/__tests__/useAlbum.tests.tsx
  src/screens/Artists/ArtistTabs/ArtistArtworks.tsx
  src/screens/Artists/ArtistTabs/ArtistDocuments.tsx
  src/screens/Artists/ArtistTabs/ArtistShows.tsx
  src/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Shows/ShowTabs/ShowArtworks.tsx
  src/screens/Shows/ShowTabs/ShowDocuments.tsx
  src/screens/Shows/ShowTabs/ShowInstalls.tsx
  src/screens/Shows/ShowTabs/ShowTabs.tsx
  src/system/hooks/__tests__/useNavigationHistory.tests.tsx
  src/system/store/Models/SelectModeModel.ts
  src/utils/hooks/__tests__/useSetSelectModeActiveTab.tests.tsx
  src/utils/hooks/useSetSelectModeActiveTab.tsx
  src/utils/test/renderWithWrappers.tsx
Labels: Jira Synced

#870 refactor(images): Refactor / optimize performance of image presentation and offline sync
  src/components/ArtworkImageModal.tsx
  src/components/Items/ArtworkImageGridItem.tsx
  src/components/Items/DocumentGridItem.tsx
  src/components/SelectMode/SelectMode.tsx
  src/screens/Artists/ArtistTabs/ArtistTabs.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Artwork/ArtworkContent/ArtworkContent.tsx
  src/screens/Artwork/ArtworkContent/ArtworkImageModal.tsx
  src/screens/Auth/SelectPartner.tsx
  src/screens/Search/SearchResult.tsx
  src/screens/Shows/ShowTabs/ShowTabs.tsx
  src/system/sync/artifacts/__generatedRelayChecksum.ts
  src/system/sync/syncManager.ts
  src/system/wrappers/CachedImage.tsx
  src/system/wrappers/SuspenseWrapper.tsx
  src/utils/hooks/useIsMounted.ts
Labels: Squash On Green

#871 fix(fullscreen): Fix darkmode pan
  src/Navigation.tsx
  src/screens/Artwork/ArtworkContent/ArtworkImageModal.tsx
Labels: Squash On Green

#873 fix(shows): ensure size consistent
  src/components/Items/ShowListItem.tsx
  src/components/Lists/ShowsList.tsx
  src/screens/Artwork/ArtworkContent/ArtworkContent.tsx
Labels: Squash On Green

#874 feat(artworks): Add more loading indicators, optimize offline images further
  src/components/Avatar.tsx
  src/components/Items/ArtistListItem.tsx
  src/components/Lists/ArtistsList.tsx
  src/screens/Artwork/Artwork.tsx
  src/screens/Search/SearchResult.tsx
  src/system/sync/artifacts/__generatedRelayChecksum.ts
  src/system/sync/syncManager.ts
  src/system/wrappers/CachedImage.tsx
Labels: Squash On Green

#881 chore(albums): Make delete album items more clear
  src/components/Lists/ArtworksList.tsx
  src/components/SelectMode/SelectMode.tsx
  src/components/Toast/ToastContext.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/system/hooks/useAppTracking.tsx
  src/system/sync/syncManager.ts
Labels: Squash On Green

#882 fix(installs): Fix install image displays + more darkmode fixes
  src/components/Items/ArtworkGridItem.tsx
  src/components/Items/ArtworkImageGridItem.tsx
  src/components/Lists/InstallationsList.tsx
  src/screens/Albums/AlbumTabs/AlbumInstalls.tsx
  src/screens/Albums/AlbumTabs/AlbumListItem.tsx
  src/screens/Albums/AlbumTabs/__tests__/AlbumInstalls.tests.tsx
  src/screens/Albums/AlbumTabs/__tests__/AlbumListItem.tests.tsx
  src/system/store/Models/SelectModeModel.ts
  src/utils/getImageDimensions.ts
Labels: Squash On Green

#885 refactor(albums): Add ability to select multiple sets of artworks in one create/edit album session
  src/components/BottomSheet/BottomSheetActions.tsx
  src/components/Items/ArtworkGridItem.tsx
  src/components/Lists/ArtworksList.tsx
  src/components/Lists/DocumentList.tsx
  src/components/Lists/InstallationsList.tsx
  src/components/SelectMode/SelectModeActions.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
  src/screens/Albums/__tests__/useAlbum.tests.tsx
  src/screens/Albums/navigation.tsx
  src/screens/Albums/useAlbum.tsx
  src/screens/Albums/useAutoSaveAlbum.tsx
  src/system/store/Models/AlbumsModel.ts
  src/system/store/Models/__tests__/AlbumsModel.tests.tsx
  src/utils/hooks/useSelectedItems.ts
Labels: Jira Synced

#886 fix(analytics): Fix a few misc tracking bugs
  docs/pull_request_template.md
  src/components/BottomSheet/BottomSheetActions.tsx
  src/screens/Albums/AddItemsToAlbum.tsx
  src/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
  src/screens/Albums/useAlbum.tsx
  src/system/hooks/__tests__/useAppTracking.tests.tsx
  src/system/hooks/useAppTracking.tsx
  src/system/store/Models/AlbumsModel.ts
  src/system/store/Models/AuthModel.ts
  src/system/store/Models/SelectModeModel.ts
  src/system/store/Models/__tests__/AlbumsModel.tests.tsx
  src/utils/hooks/useMailComposer.ts
Labels: Jira Synced, Squash On Green

#887 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#888 feat(unleash): Add unleash feature flag support
  .env.example
  package.json
  scripts/utils/refresh-env-variables
  src/Boot.tsx
  src/Navigation.tsx
  src/components/Lists/ArtworksList.tsx
  src/setupJest.ts
  src/system/hooks/useAppStatus.tsx
  src/system/hooks/useFeatureFlag.ts
  src/system/hooks/useSystemIsDoneBooting.ts
  src/system/providers/AnalyticsProvider.tsx
  src/system/providers/FeatureFlagProvider.tsx
  src/system/providers/ThemeProvider.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#889 fix(analytics): Update types
  package.json
  src/system/hooks/__tests__/useAppTracking.tests.tsx
  src/system/hooks/useAppTracking.tsx
  yarn.lock
Labels: Squash On Green
